### ISSUE TITLE
[Inconsistent API]: GetAllUsers -> lecturer

### ISSUE THREAD

**Issue by theovier** [upb-uc4/api#9]
The call to GetAllUsers returns 3 arrays

1. admin**s**
2. student**s**
3. lecturer

I hereby request to rename lecturer to **lecturers** (with plural "s") to stay consistent.

**Comment by bastihav** [comment]
Did you check the actual API response? I think this is already implemented on both sides, might just be a typo on swagger

**Comment by theovier** [comment]
Did check. Cost me roughly 40min.

**Comment by theovier** [comment]
I'll checkout the newest develop branch of lagom tomorrow and test it again, but if it wasn't fixed since the weekend, I reckon it is still around.

**Comment by bastihav** [comment]
This is indeed a typo in swagger and a bug in lagom in the case class GetAllUsersResponse

@dhelmert

**Comment by janniclas** [comment]
What I forgot to mention regarding swagger, u might want to check if you can generate your swagger file from your servers code. 
In my experience this greatly helps to permit inconsistencies like these. 
In nest.js for example you can just add annotations to your code and get a swagger spec for free. For me this makes more sense, since you usually need a spec describing your server and generate code for the consumers/clients. 
If you write the swagger manually you always have to sync both sides.

**Comment by lrschaef** [comment]
Fixed in v0.5.0
